### ISSUE TITLE
How to run examples?

### ISSUE THREAD

**Issue by bartonhammond** [alexschwarz89/browserstack#2]
Not sure how to run this, I'm new w/ Php.

Steps I did

- `cd examples`
- create `composer.json`
```
{
  "require": {
   "alexschwarz89/browserstack": "0.0.2"
  }
}
```
- `composer install`
- `composer exec generateScreenshots.php `

Result:
```
composer exec generateScreenshots.php 
Script generateScreenshots.php handling the __exec_command event returned with error code 127
```

**Comment by alexschwarz89** [comment]
Hi,

i never tried "composer exec" but you should just run it with "php generateScreenshots.php"
